# Working with the Bash Shell.

The "Bash Shell" command line interface has become a 
## Ryans Tutorials 
## Download files for use in these lessons

A "zip file" is a single file that contains a condensed version of one or more 
files or folders. Click on [this link](files/myFiles.zip) to download a "zip file" 
named myFiles.zip that contains files
that we will be working with to demonstrate many of the commands available
with the Bash CLI. 

To "extract" (or unzip) all of the files that are in this zip file, run the following 
command:

```
unzip myFiles.zip
```




### Vocabulary related to folders (also known as "directories")

- A "directory" is a "folder"
  The word "directory" is a synonym for the word "folder". 
  They two words mean the EXACT SAME THING. 

- The "parent" of folder/direcotry, x, is the folder/directory that contains x.


### Important Bash commands that everyone should know

The following gives a brief description of how many commands work.
In the descriptions below, any part of the command that appears
in [square brackets] is optional.


- pwd                  - "Print the Working Directory" (ie display the "path" for the current working directory (CWD)

- cd SOME_DIRECTORY    - set the "working directory" to the specified directory
- cd                   - set the "working directory" to your "home directory"
- cd ..                - set the "working directory" to the "parent" of the current working directory
- cd ../..             - set the "working directory" to the parent of the parent of the current working directory
- cd ../../..  (etc.)  - set the "working directory" to 3 levels up in the directory hierarchy)

- mv SOME_FILE  SOME_DIRECTORY           - move SOME_FILE to SOME_DIRECTORY
- mv SOME_DIRECOTRY  ANOTHER_DIRECTORY   - move SOME_FILE to ANOTHER_DIRECTORY

- ls [SOME_DIRECTORY]         - list the files in the current directory or the specified [DIRECTORY]
- ls -l  [SOME_DIRECTORY]     - show a "long" listing (i.e. more info about each file/folder)
- ls -r  [SOME_DIRECTORY]     - reverse the order that the files are listed
- ls -lt [SOME_DIRECOTRY]     - show the contents in time order (with a long listing format)
- ls -l -t [SOME_DIRECOTRY]   - SAME THING - show the contents in time order (with a long listing format)
- ls -a  [SOME_DIRECTORY]    - show all files (including files that start with a period ( . )
- ls -R  [SOME_DIRECTORY] - show the files that are in all folders below the CWD (or the specified directory)
- ls SOME_FILE                - list the name of the 

- cat SOME_FILES              - display the contents of the files (only for "text" files)

- tree .                      - show directory hierarchy (is not installed on many systems)

- code                 - launch the VSCode text editor program (if you've installed it)
- code [SOME_FILE]     - launch VSCode and open SOME_FILE
- code [SOME_DIRECTORY]     - launch VSCode with the "explorer" window set to SOME_DIRECTORY.
- code .   (there is a period there) - launch VSCode with the "explorer" window set to the current working directory.


## creating files using > and >>

- echo SOME_MESSAGE                - display the message
- echo SOME_MESSAGE > SOME_FILE    - put the message in the file (erase current contents of file)
- echo SOME_MESSAGE >> SOME_FILE   - append the message to the file

## creating/removing directories (aka folders)

- mkdir SOME_DIRECTORY  - "make" the specified directory
- rmdir SOME_DIRECORY   - "remove" directory (must be empty, NOTE also see rm command)

## Removing files

BE CAREFUL WITH THE FOLLOWING COMMANDS!!!  
***THERE IS NO UNDO***  
ONCE YOU'VE REMOVED A FILE/FOLDER YOU CANNOT GET IT BACK!

- rm SOME_FILES   - remvove the files (THERE IS NO WAY TO GET THEM BACK)
- if you are brave, you can research how to use rm to remove entire directories (that aren't empty)

### SOME MORE COMMANDS - search online for info about these

- wc - count words, lines, symbols in a file
- head   - show first few lines of a file
- tail   - show last few lines of a file
- sort
- uniq
- cut
- paste
- curl    - download files from the Internet
- touch SOME_FILE       - update the timestamp of the file OR create the file if it didn't exist
- less (or "more" depending on your system) - display the contents of a file one page at a time
- grep - search for a specific string of text in a file or multiple files
- find - search for files and directories in a file system
- chmod - change the permissions of a file or directory
- chown - change the ownership of a file or directory
- history - display a list of previously executed commands

### Working with ZIP files and TAR files

- zip -r FILENAME.zip SOME_FOLDER   - creates a new zip file
- unzip FILENAME.zip                - extracts the contents of a zip file
- gzip / gunzip   - zip/unzip Gnu types of zip files
- tar - create or extract a tar archive
