# <yrChapterNumber></yrChapterNumber> Chrome Extensions

A <yrDef>chrome extension</yrDef> is a piece of software that extends 
the capabilities of the Chrome browser.
## How to install a Chrome Extension

First make sure that you have the Chrome browser installed. 

Then, click here for info about how to install and use a chrome extension.

<https://www.youtube.com/watch?v=g92v8bP8dKo>

## Try it yourself

* Try installing an using the "google dictionary" chrome extention

* Try installing an using the "google translate" chrome extention

## Using other browsers

Chrome extensions may work in other
browsers as well, but Chrome is the best option to make sure that the extension
works as intended. 

The following was generated by chatgpt on Jan 22, 2025 - As with all info
generated by AI today, this may not be totally accurate. Proceed at your 
own risk :)

<blockquote>
<yrLlm date="Jan 22, 2025" url="https://chatgpt.com/c/679126a0-d258-800b-8e33-316bb37b7e97">
Me:
can i install a chrome extension in other browsers ?

ChatGPT said:
Yes, many browsers support Chrome extensions, but compatibility depends on the browser:

1. Microsoft Edge: Directly supports Chrome extensions. Go to the Edge Add-ons Store, enable extensions from other stores, and install from the Chrome Web Store.

2. Opera: Requires the "Install Chrome Extensions" add-on to enable Chrome extensions.

3. Brave: Fully supports Chrome extensions without additional steps. Install them from the Chrome Web Store.

4. Vivaldi: Supports Chrome extensions. Install them directly from the Chrome Web Store.

5. Firefox: Does not natively support Chrome extensions. Extensions must be specifically built or converted for Firefox.

6. For non-Chromium-based browsers, like Safari or Firefox, Chrome extensions won't work directly without conversion or dedicated versions.
</yrLlm>
</blockquote>

## Developing your own Chrome Extensions

Using modern AI, it is often possible to develop your own custom Chrome 
extensions. We will not go into that here, but the adventurous are free to 
experiment on your own. 

While under development a Chrome extension consists of several files in a 
folder. Once the coding of the Chrome extension has been completed, the entire
folder with all of the necessary files can be compressed into a single zip
file. It is this zip file that can be upladed to the Chrome Extension store.

### "unpacked" Chrome extensions 

While under development, a Chrome extension can still be installed in Chrome
without needing to ZIP up the folder. Follow the instructions here
to use a chrome extension that is still under development. You will need to 

1. unzip the folder if it is zipped

2. navigate to the url  <chrome://extensions>

3. Click the "developer mode" switch

4. Click "load unpacked"

Chrome extensions are created using standard web development languages
(i.e. HTML, CSS, Javascript). 

You can follow the instructions in this video:


<https://www.youtube.com/watch?v=yNFwFQrc27Q>


## Using the yrWebSnip chrome extension

### Download the code for the extension

1. Go here <https://github.com/y-rosenthal/yrWebSnap>

2. Click on the "<> Code" button and choose "Download ZIP"

3. Unzip the file to a folder (search online if you don't know how to do that)





