# Generated by chatgpt
# URL: https://chatgpt.com/c/67c4bd29-2514-800b-9165-ce12c3075108
# Topic: Automating QMD file Zipping

# Also see claude.ai
# URL: https://claude.ai/chat/bb5842db-a217-4e07-ae74-9f96eae78e9e
# Topic: Working with Zip Files
if(!require(zip)){install.packages("zip");require(zip);}


# files <- list.files(pattern = "\\.qmd$", full.names = TRUE)
# 
# for (file in files) {
#   zipfile <- file.path("_book", paste0(basename(file), ".zip"))
#   zip::zip(zipfile, file)
# }
# warnings()

files <- list.files(pattern = "\\.qmd$", full.names = TRUE)
for (file in files) {
  zipfile <- file.path("_book", paste0(basename(file), ".zip"))
  # Use the root parameter to avoid ./ in paths
  zip::zip(zipfile, files = basename(file), root = dirname(file))
}
